// <auto-generated />
using System;
using Hochwaerts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hochwaerts.Migrations
{
    [DbContext(typeof(HochwaertsDBContext))]
    [Migration("20260303081329_OneTOmanyOptional")]
    partial class OneTOmanyOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Hochwaerts.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuchId");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("Hochwaerts.Models.Bibliothek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bibliothek");
                });

            modelBuilder.Entity("Hochwaerts.Models.Buch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Beschaedigungsgrad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Erscheinungsjahr")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buch");
                });

            modelBuilder.Entity("Hochwaerts.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zustand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Hochwaerts.Models.Verleihobjekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BibliothekId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuchID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZaubererId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BibliothekId");

                    b.HasIndex("BuchID");

                    b.HasIndex("StatusId");

                    b.HasIndex("ZaubererId");

                    b.ToTable("Verleihobjekt");
                });

            modelBuilder.Entity("Hochwaerts.Models.Zauberer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Haus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zauberer");
                });

            modelBuilder.Entity("Hochwaerts.Models.Autor", b =>
                {
                    b.HasOne("Hochwaerts.Models.Buch", "Buch")
                        .WithMany("Autoren")
                        .HasForeignKey("BuchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buch");
                });

            modelBuilder.Entity("Hochwaerts.Models.Verleihobjekt", b =>
                {
                    b.HasOne("Hochwaerts.Models.Bibliothek", "Bibliothek")
                        .WithMany("Verleihobjekte")
                        .HasForeignKey("BibliothekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hochwaerts.Models.Buch", "Buch")
                        .WithMany()
                        .HasForeignKey("BuchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hochwaerts.Models.Status", "Status")
                        .WithMany("Verleihobjekte")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hochwaerts.Models.Zauberer", "Zauberer")
                        .WithMany("Verleihobjekte")
                        .HasForeignKey("ZaubererId");

                    b.Navigation("Bibliothek");

                    b.Navigation("Buch");

                    b.Navigation("Status");

                    b.Navigation("Zauberer");
                });

            modelBuilder.Entity("Hochwaerts.Models.Bibliothek", b =>
                {
                    b.Navigation("Verleihobjekte");
                });

            modelBuilder.Entity("Hochwaerts.Models.Buch", b =>
                {
                    b.Navigation("Autoren");
                });

            modelBuilder.Entity("Hochwaerts.Models.Status", b =>
                {
                    b.Navigation("Verleihobjekte");
                });

            modelBuilder.Entity("Hochwaerts.Models.Zauberer", b =>
                {
                    b.Navigation("Verleihobjekte");
                });
#pragma warning restore 612, 618
        }
    }
}
